services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  controller:
    build: ./controller
    container_name: controller
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./controller:/app
    env_file:
      - ./controller/.env

  worker1:
    build: ./worker
    container_name: worker1
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./worker:/app
    env_file:
      - ./worker/.env
    environment:
      - WORKER_NAME=worker1

  worker2:
    build: ./worker
    container_name: worker2
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./worker:/app
    env_file:
      - ./worker/.env
    environment:
      - WORKER_NAME=worker2

  worker3:
    build: ./worker
    container_name: worker3
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./worker:/app
    env_file:
      - ./worker/.env
    environment:
      - WORKER_NAME=worker3